### ISSUE TITLE
Official hub.docker.com MISP organization with containers: misp and misp-modules

### ISSUE THREAD

**Issue by 8ear** [MISP/misp-modules#468]
Hi Guys,
I love Docker really much and I love if the container are created daily with the latest security updates and come directly from the "vendor" :-).
In the case of MISP I like that we reached the state to have a dockerfile for misp-modules, but I miss the hub.docker.com organization for that and the regular automatic build.

So I will ask you @adulau and your colleagues if it is ok if I setup this for you?

## Todos
In detail I mean:
- [ ] Create a free MISP hub.docker.com organization
- [ ] Create a MISP-bot hub.docker.com user
- [ ] Create a MISP-bot github.com user
- [ ] Link the MISP-bot github and hub.docker.com user
- [ ] Add hub.docker.com MISP-bot secrets to Github MISP organization
- [ ] Add github Workflow so that a daily build is made of MISP-modules  and for misp-docker

## Goal
The result should be that MISP has hub.docker.com misp/misp and misp/misp-modules docker images which are daily recreated.

## Requirements
For this I need support also from you:
- a release from you to do this 
- That you add the misp-bot user as member to MISP organization

After this action I will give you the credentials from hub.docker.com bot user and from github bot user so that you can change the passwords.

If any is unclear I am happy if you get in touch with me.

**Comment by chrisinmtown** [comment]
Is this issue perhaps more appropriate for the repository https://github.com/MISP/misp-docker ?

**Comment by 8ear** [comment]
It is for both. But you are right. I will move it to the other repo.
