### ISSUE TITLE
cof2misp checklist

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/misp-modules#493]
@aaronkaplan 's todo list for the cof2misp module

# Coding
- [x] strict validation  (but the simple validation shall be the default) -> as discussed not necessary
- [X] zone_time_*
- [x] unit tests
- [x] dnsdbflex
- [x] make sure the sharing is by default "this-org" only (distribution)

# Misc and documentation
- [x] LICENSE
- [x] install instructions
- [x] how to get keys from farsight --> send draft to Boris
- [x] presentation FIRST
- [x] update FIRST SIG page 
- [x] draft blog post

--> in a later project as agreed: - [ ] relationships amongst objects

**Comment by aaronkaplan** [comment]
dnsdbflex: https://github.com/MISP/misp-objects/pull/315

**Comment by aaronkaplan** [comment]
Unit tests are in `` ``.
Results of the unit tests:

```bash
(venv) root@misp:/usr/local/src/misp-modules# source /var/www/MISP/venv//bin/activate
(venv) root@misp:/usr/local/src/misp-modules# python misp_modules/lib/cof2misp/cof.py 

================================================================================
Unit Tests:
is_valid_ip(a.2.3.4) returned False. Reason: 'a.2.3.4' does not appear to be an IPv4 or IPv6 address
================================================================================
COF unit tests....
line 0 is valid: True
line 1 is valid: True
================================================================================
dnsdbflex unit tests....
dnsdbflex line 0 is valid: True
dnsdbflex line 1 is valid: True
dnsdbflex line 2 is valid: True
dnsdbflex line 3 is valid: True
dnsdbflex line 4 is valid: True
dnsdbflex line 5 is valid: True
================================================================================
Unit Tests DONE
```

**Comment by aaronkaplan** [comment]
The default sharing distribution flag is now set to "your organisation only", as requested.
See the screenshot below.
<img width="1277" alt="Screenshot 2021-06-17 at 16 16 12" src="https://user-images.githubusercontent.com/750019/122414756-ab83ac80-cf87-11eb-9c3f-da2a85035514.png">

**Comment by aaronkaplan** [comment]
closing, all done.
